# Generated by Django 2.2.3 on 2019-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_game', models.CharField(choices=[('LOL', '리그오브레전드'), ('OW', '오버워치'), ('PUBG', '배틀그라운드')], max_length=20)),
                ('c_name', models.CharField(max_length=20)),
                ('c_date', models.DateField()),
                ('c_time', models.TimeField()),
                ('c_tag', models.CharField(max_length=10)),
                ('c_rule', models.TextField()),
                ('c_rule_file', models.FileField(null=True, upload_to='')),
                ('c_prize', models.TextField()),
                ('c_schedule', models.TextField()),
                ('c_contact', models.TextField()),
            ],
        ),
    ]
